### ISSUE TITLE
`getFileHandle(create: true)` throws `NotFoundError` in a valid direcotry.  

### ISSUE THREAD

**Issue by Cat-sushi** [poirierlouis/file_system_access_api#1]
```yaml 
 file_system_access_api:
    dependency: "direct main"
    description:
      name: file_system_access_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
```
```console
$ flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (2 days ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

![Screenshot from 2022-12-17 17-29-38](https://user-images.githubusercontent.com/10280770/208233493-acdcb066-8e34-4b73-b246-092903c70863.png)
